spring:
  application:
    name: springarchitecture
  jpa:
    show_sql: true
  main:
    lazy-initialization: false

app:
  automaker:
    standard-engine: 130
  config:
    variable: value of variable x
    value1: 500